services:
  postgres:
    image: postgres:18.1
    container_name: postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - lofi-lab-network

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin-server
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-test@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-postgres}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DISABLE_POSTFIX: "True"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
    ports:
      - "${PGADMIN_PORT:-5433}:80"
    volumes:
      - ./pgadmin-data/servers.json:/pgadmin4/servers.json
      - ./pgadmin-data/pgpass:/pgpass
    depends_on:
      - postgres
    networks:
      - lofi-lab-network

networks:
  lofi-lab-network:
    driver: bridge
