# Fluent Bit configuration for nginx logs
# This file should be copied to /etc/fluent-bit/conf.d/ when deploying the service

pipeline:
  inputs:
    - name: tail
      path: /var/log/nginx/access.log
      tag: nginx.access
      db: /var/lib/fluent-bit/nginx-access.db
      parser: nginx_access

    - name: tail
      path: /var/log/nginx/error.log
      tag: nginx.error
      db: /var/lib/fluent-bit/nginx-error.db
      parser: nginx_error

  filters:
    - name: modify
      match: nginx.*
      add:
        service: nginx
        host: ${HOSTNAME}

  outputs:
    - name: loki
      match: nginx.*
      host: 10.0.0.2
      port: 3100
      labels: job=nginx, service=lab-proxy, host=${HOSTNAME}
      line_format: json
      workers: 1
