up:
    nerdctl compose -f caddy-compose.yaml up -d

down:
    nerdctl compose -f caddy-compose.yaml down

logs *ARGS:
    nerdctl compose -f caddy-compose.yaml logs {{ARGS}}

reload:
    nerdctl exec -it caddy-server -- caddy reload --config /etc/caddy/Caddyfile

dns:
    #!/usr/bin/env bash
    sudo cp dnsmasq.conf /etc/dnsmasq.conf
    sudo systemctl restart dnsmasq.service
