apiVersion: ENC[AES256_GCM,data:+3g=,iv:y76sRHAgcPvh6VVcbD/dZgLxC8hYVTKpwrSjCTSNMlw=,tag:FOpDrfLe8ycu8VYhsAQDVw==,type:str]
kind: ENC[AES256_GCM,data:BXeWBxtM,iv:MuchJVXyLtUIaLttnjQV73iPzvBUhLrIYHJbBLF4LJg=,tag:h8G3gwwu6ytQzBx4A5nrlQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DJtlCdcVhI95CGcjAlxlvaNJRg0ntQWN1yxcEtwH,iv:4JKShPEx4wvOKnRzcoCN+X4XxAddfwwVs7WfSgW+nHY=,tag:59+BnP5rbMjRC+7lmL1uXw==,type:str]
    namespace: ENC[AES256_GCM,data:xC7aDWD7QnQC,iv:mvbGGaRbTOODk3xuu0IZiI5z+F+bRWng2hHThyK4onw=,tag:cUWM0b9+jZvTAtSA1dpugw==,type:str]
type: ENC[AES256_GCM,data:XJzrfzo3,iv:dNAhjxobzFsrUQIIhIXPifYgtig1Tqen1MoFLnQU/fc=,tag:FLeESYR3pDxJJXRWSx18JQ==,type:str]
stringData:
    email: ENC[AES256_GCM,data:nE7BCbm9hoyBF8ks1+4=,iv:Zhb9CRH8O1skvZApmrPovG0r+7p6MDuLo0sOS5iu+Rw=,tag:zpH+Oqh5x2ObDNY2ecDBuQ==,type:str]
    password: ENC[AES256_GCM,data:wfV/kJ7NvopnBERmuDVSy4f8QRV9I2k=,iv:LI8OPTqrD/2xnLX+NDU3bdQLDuApvySwO1WQDOLgcRw=,tag:KKfiMZyHZIbRX8oVaIWcdw==,type:str]
    #ENC[AES256_GCM,data:ZEtBRF5Z0OYuL+xwY4tBXO1qij7Z0eph6UlLdwPNCOi+yNaB7FMFK9+FlJg=,iv:UKaTMKx+996S5+OJbzq2Xi8orGKkea+4YRJwODDolf0=,tag:nD7NgX1putlQT/HYUphsaA==,type:comment]
    #ENC[AES256_GCM,data:7i4QKFck87nJC3yapDrp1OgZJF1ppGVdChlGNmGYwB4=,iv:7xKnU54O8oNaEtwnUGzgIeZwaP5n0xfrV1o4ZYCERlc=,tag:+eWt69/wnm2MJBc9B2C0PQ==,type:comment]
    workspaceName: ENC[AES256_GCM,data:U79DUxGuv2w=,iv:sQ3MvzS3sFflzRHkzxrrPc7Yx3Uh82aEslsrFWdqX7I=,tag:AUjaN8vIXMmfpbu234ucyQ==,type:str]
    #ENC[AES256_GCM,data:Ra1/aFb1iAcvHTmiFTZfc4Ut7ABriLFFaKNJW/eSnCNjwZPDfDF1gJHIBybxFfiGpXESu6gijpKCMabM05ReRg==,iv:GlH1xM6bcVy6/ynctyXtNwzdMYE6XLzjr9JUsoGAUaI=,tag:aw7dIFarCp9JmwqmM4c10Q==,type:comment]
sops:
    age:
        - recipient: age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM1ZRM0VGVjZEUGdmZkhT
            RFNGNnhvZnlaTHhwYUFGcmk3dGdUTmpBZVRZCndIWFFQUngwbzhvZ1hnQ1hyL014
            TmRXOVZ6ZTFwOFR6UTRMKzFraEZvWFUKLS0tIGRMSHREUGoyU0NIbHVyZnFrTW4v
            Rk84OHNmMUJlNFNFS3pEYWtRZ3hEeVEKayBtli4Ocz3dIQYZLO0ZafviXqQbP8uF
            0cvseugSkK6pySUJA2yF0tfOLfKLhmTm+WvhbDYJ9ZcWIv8m5c5Y/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv7v50lygkd88nqhmy7mnxyp9jvaqmet6wdccc0zsvdjxf3t0emq4rmwrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSjhjZ1lhRk55ZVFweEZ5
            SXVCYkJKMER1MFBvUWd6ZTJtaUJUV01CN0ZVCjhGMUYwK0RiZVRWQjlTcCthL2sy
            YWJNZDBwcG1SeE9adWU4SWFFUSt4OHMKLS0tIGF0cVFnemhxNTBRZlAyaDVaVVBu
            S2grZmZRMVVobVJwNFNSRDFnSXVxMnMKk33WRVLfCtc5jkCTQDUaT6g9Y/dxfqp7
            4HztFAkSOsfLGHhrxV01lRdmknc0OasNRwvnlejgscpL7gJcaB5e6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s59a0sgvuqutt9kyck3cz347g0mlzgrjg6z3ushzyp2jxy5h9gnqsjfj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYms0bzVSTE9ReGpVUFNB
            SVRkNDRZeUpmSm1wT0xjeDBPU1dKSmJMMnpVCndFZHc2QlJxSjVGSE4rS1JGY1Iv
            TWVwS1Zsd1k0bXJQNGNqb0Uzc0YxMEEKLS0tIGIrUVFaZ0dMNDE0Wms4TDBibmp4
            bG5vbnZibXlPeUl2ZXRIS0FCN1dxYUEKVRQFUYegBtpiNzqXMHt0h/rNJrJhK3uL
            0ib4xjZvYL/GblyY/u6UcHXXTAjJV//Z1//AQiggI3M9v1O2nyFKUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7umu2tev8057x4qte4g8smua7nqhdhqmrk49pq9xpx6zxc0p3qjurnlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QWtQZmpUalBQN0ZaYlg5
            bFhzYXNHajdLVis4TVNLaE9PMkpQTXFGNHdzCmx3WTNmcnlVckVNK0Q0OWtVbmov
            UXNGR3Z2WDk2ZVg5SjBIV25PYXVzTzQKLS0tIEVhMFFXQnlYMm05ajgyeW04anNW
            OXN0NUhQYkNVaityQWhNbmNRbG9OUEEKHJtCkCD8otWkLys135oRgJOEqexTxZDl
            KQo19qE9xI9L3E8YJGoCKYQbhdJCg+QqSnGiK+8tA5MzmCnSGMd2Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T00:48:03Z"
    mac: ENC[AES256_GCM,data:ytBZ8IRInVGfFxl5LcdxZgVdybkxkKXBucGvehofs1vjgwEoFVgVYHbjtNZZ2qbTQSIq58BbNXM7/FmwqrsN8p3mcvVuu7q5XF6dKz0xcujmhry+TCg95PvWBKeQIxUVoDMMiObp2Dn3q/18/MY4+rACkx35jMLmGUpHTotN4OI=,iv:SJAd2wpZI3yX934Ec6ksHiQMD1EVIw+yn7R5WtVtOLg=,tag:506Rkb2AmwPMAK7rVQQm1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
