services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    # environment:
    #   HOMEBRIDGE_ORIGINS: '10.0.0.*'
    ports:
      - ${HOMEBRIDGE_PORT:-8581}:8581
    volumes:
      - ~/.homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s

