services:
  dolibarr:
    image: dolibarr/dolibarr:16
    container_name: dolibarr-server

    environment:
      DOLI_DB_TYPE: "pgsql"
      DOLI_INIT_DEMO: ${DOLI_INIT_DEMO:-0}
      DOLI_DB_HOST: ${DOLI_DB_HOST:-postgres-server}
      DOLI_DB_NAME: ${DOLI_DB_NAME:-dolidb}
      DOLI_DB_USER: ${DOLI_DB_USER:-steven}
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD:-secret}
      DOLI_URL_ROOT: "${DOLI_URL_ROOT:-http://0.0.0.0}"
      DOLI_SERVER_NAME: "dolibarr.lofi"
      DOLI_ADMIN_LOGIN: "${DOLI_ADMIN_LOGIN:-admin}"
      DOLI_ADMIN_PASSWORD: "${DOLI_ADMIN_PASSWORD:-admin}"
      DOLI_CRON: ${DOLI_CRON:-0}
      DOLI_CRON_KEY: ${DOLI_CRON_KEY:-mycronsecurekey}
      DOLI_COMPANY_NAME: ${DOLI_COMPANY_NAME:-MyBigCompany}
      WWW_USER_ID: ${WWW_USER_ID:-1000}
      WWW_GROUP_ID: ${WWW_GROUP_ID:-1000}

    ports:
      - "11020:80"

    volumes:
      - ./dolibarr-data/documents:/var/www/documents
      - ./dolibarr-data/custom:/var/www/html/custom

    networks:
      - lofi-lab-network

networks:
  lofi-lab-network:
    driver: bridge
