#ENC[AES256_GCM,data:wWZkjwynNSCQ3agChMd8Vv8N7sDK5q90JwWLWXJr7ZeJzg==,iv:hplxPjw8v6fvdwG4p8iZoBQbLfxjl4CjvXkqcqIgUkM=,tag:I+4oLmBP1YpmQd0Se2kTPA==,type:comment]
#ENC[AES256_GCM,data:Fkrd5iDpPImJJ6XntLxZRtN8pMBuOkVV7xkO+iX/2SJREMw=,iv:vleenoXoeLM3M81pmQ/4urXwuXhm903irUaTFw7uYxA=,tag:9xXQgo2MjZa/9La8kSGoTw==,type:comment]
#ENC[AES256_GCM,data:aEE+0/R8tKwvRjpBQ7oT5+/Xk/vkfuIjTMV+ELzVB0wtH5HGbd3U,iv:pb/WpTf0LOs+/wADBZKyIusiHroVdurrQKn9gEw4xR0=,tag:X20egbWe+nimZGcNCj88AA==,type:comment]
#
#ENC[AES256_GCM,data:yLEFKCimeqUWCFipZ0f3Cg0PEvnhj4jmsJW/zaiUC3Jb4f6qgduFl8ztDNUb2pCOyWh+vGQRsQ4mL/FxVJnIyhb+KrlNCmL3a0tumqR4xnwnhkA=,iv:g/dH5yuv0n2Rzs1r0SB43w6y4NpVmVR4r0qDFtpo0EQ=,tag:dUZYbUoNUsQY9cDSkaI3/A==,type:comment]
#ENC[AES256_GCM,data:RIel0M7HA4aq31blSiUgcqNpioeX6Jec7gdkqt9a7YUwcaw06YjUoe50o/o3vkFCLE96Bs34FLl0xfOHsRV8q+3VeX5HGyRLwlLOSH5k5Xi/SvP4,iv:R1LBaavj3Uwr1rjmYBnvLXYfNNqnX3qk4edWyk7stb8=,tag:yvW2MJHvkLtB7Fd6pCwgFw==,type:comment]
apiVersion: ENC[AES256_GCM,data:mos=,iv:hrWAfDfs8zQiccF7MKa5/fWRHdmkx1s/IDK4cVc2WVg=,tag:KdCCzXOHbDtTJEYi5+gBLQ==,type:str]
kind: ENC[AES256_GCM,data:X8N265k+,iv:a+PW/PYfo1izjepZgFCU2Bp8UQFJJSRpXlY5XrGLnoY=,tag:DeKXJN2Z0/ZYpVy8QaA8iQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:90guM7d84KIM71RmwrWNPGRz,iv:MtVhd0L0wfpyB0noyf4JNxsCogdhcYD0ELrLFaLQVpY=,tag:E7UaZMuWoaksIivC32WOfQ==,type:str]
    namespace: ENC[AES256_GCM,data:pO3/SpN7,iv:4UxEoCO+NN5Q1hMWXEWuHAaDbyTVSCjSGrWZgX7Vgo0=,tag:W9+AzbVUlHPpgkdRpIGVFQ==,type:str]
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:l6Gha1975QCobZS90sKKHVHxU3lxBEY8VDX8p//sEZjyTFe/3c65avmWAVbKsC/RfXSllptyPkZZnPZaoj0wZw==,iv:Fz+XgfG1BXCdFZq8/TkCmYOvgYroB/sswgJNFbmP8pE=,tag:NwK65aa71VzD+l3j3Z+xAA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:/4KL1uiPv+UH1BT9dQnb1QLJM3WRaLyUfwCGpvzJFuqTQGtrBQhExkCPYQNeE0CfiYtkU3UYHvUjehova15lCA==,iv:LPjKcSJUewZUfZ5xxyJbtieD/KJ/j83QXsXibNNvuUc=,tag:dhyrXHDUmGHBFz+DWO8eFA==,type:str]
sops:
    age:
        - recipient: age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWVZZWtIS25GUDRsc1cz
            YnVSNThlWjlTUHFuZVV3ck9rbi9oTUF4QUJJCjd5TnZCREVZenBhajNEVXk0ZFNj
            L3dJUXEvNThvbjNFS1BSMHludi8zWkkKLS0tIDJaYmNBMFhqMk0vcWNIVDdGRkhO
            RGNBa1EwOUxzMG5HZTVrb0ZKTDZ1VnMK7tYSgfNAc7wbdaOsFvEEptCxu/SXKKfd
            tWE2hxhZMZkaNi6MOqzvfhXytdclP2aP54WPjDPdNanM+xw21Zdbnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv7v50lygkd88nqhmy7mnxyp9jvaqmet6wdccc0zsvdjxf3t0emq4rmwrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNnFYQ1RpRGZIZFhHaGx2
            NlZERy9Bd0JVY1VGV0hXKzg3KzVJbTR3c1ZvCitsTkdDQ29GdEJOVkErS3BoNGJk
            QmxiUTJsbUFDL0s2WWJZUzdmYnZQd0UKLS0tIGZlenl5RW5QTmRzWFltWnhtUllP
            Q3dENWZjRTNkYzBXNXlOQ2l4OWtBWGMKA3Vscu0abfVjDaz6ulHrG4bCswCZJlhE
            hsQfAV6Q8xQWrzW16Y+3y8VUzqwl5dSkwk61/mNtaJydoVRdA2YkVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s59a0sgvuqutt9kyck3cz347g0mlzgrjg6z3ushzyp2jxy5h9gnqsjfj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd3BhVi8vamlXY1V3a09S
            akNhWlhRTHZNNXlpVXROUmhNelNVcVFVd21rCkVmZFhFZmI3bjVvL09FUld1UHVE
            R2sydzVZUjB2QUFrK0srWFRvbXpaUWsKLS0tIG5oNEZ3cGI3Zm5MdlJGZDd1bVFk
            aEs4ZW5TSWQxMW5JZWRjUU4ra1NOZk0Kfr/sZpUucs6Z75hC4Aky7GcYjJ83WIwA
            hQOOFO46Zgm4Thu35LZIff/lM9UCHbXdW9nlv/DMsvKzhvhl/+XfSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7umu2tev8057x4qte4g8smua7nqhdhqmrk49pq9xpx6zxc0p3qjurnlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TFpXanlMcW03ckFqdWhw
            L09obkxnYVhPTU5OdXFxMzJDOHhTUTdNYkNzCjZFQVg2eWw4SHc2T0w0dWpKQVQ0
            UGFRanlsTzlVdUVNdHFOMjZZZUdXU2cKLS0tIGhPMVgzdGhQWVhXMVFBcEpzem0r
            MGw1eEltRi9hMHNzWUIxNXVuVkEyVGcK8C/DOegeXnDUIlVYRbbuiFzUY7PjGw/V
            IS0LUr8lTgNKGgLZe6azw2FCiwsttrR2+h7zV9SxkJCLHrWLcr4wuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T07:32:02Z"
    mac: ENC[AES256_GCM,data:tCs/POywvRfT52R6j/NNOTgDSPBDPB7gk4ESEWRmRj/t6QYKAn64TSBcJzJ+9QBwKOOheHxQt+2yqqsXD4TkNyDJBINUYewoUpLo9TW923xDRVbT1sDTlrdPVbH64agGG+7HG9lEHZevj+ubhcbNc92Ci+Gs32gXwTKeMSs1rX4=,iv:Q3fOWo4gFichMCGKtvyzphl7GufpR4Isc5e9WWNdmH4=,tag:muDp83OVD28wq/zSx78/kQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
