- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true
  tags: apt

- name: Install required packages
  apt:
    name:
      - gcc
      - git
      - make
      - tmux
      - unzip
      - zsh
    state: present
  become: true
  tags: apt

- name: Clone dotfiles repository
  git:
    repo: https://github.com/sf1tzp/.files.git
    dest: ~/.files
    version: main
  tags: dotfiles
  args:
    creates: ~/.files
  failed_when: false

- name: Create directories in ~
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config
    - ~/.local
    - ~/.local/bin
  tags: dotfiles

- name: Create symlink for zsh profile
  file:
    src: ~/.files/shell/zsh/profile
    dest: ~/.zshrc
    state: link
    force: yes
  tags: zsh

- name: Change default shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  tags: zsh
  become: true

- name: Install zplug
  git:
    repo: https://github.com/zplug/zplug
    dest: ~/.zplug
  tags: zsh

- name: Install TPM (Tmux Plugin Manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags: tmux

- name: Create a sym link for ~/.tmux.conf
  file:
    src: ~/.files/shell/config/tmux.conf
    dest: ~/.tmux.conf
    state: link
    force: yes
  tags: tmux

- name: Install fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1
  tags: fzf

- name: Run fzf install script
  command: ~/.fzf/install --bin
  args:
    creates: ~/.fzf/bin/fzf
  tags: fzf

- name: Install bins
  command: ~/.files/shell/scripts/install.py
  tags: install_script
  environment:
    AUTOMATIC: "true"
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Install Rust
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile minimal
  args:
    creates: ~/.cargo/bin/rustc
  tags: rust

- name: Install Go
  shell: |
    curl -L https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz -o /tmp/go.tar.gz
    tar -C /usr/local -xzf /tmp/go.tar.gz
  args:
    creates: /usr/local/go/bin/go
  vars:
    go_version: 1.24.2
  become: true
  tags: go

- name: Install Neovim
  shell: |
    curl -L https://github.com/neovim/neovim/releases/download/v{{ nvim_version }}/nvim-linux-x86_64.tar.gz -o /tmp/nvim.tar.gz
    tar -xzf /tmp/nvim.tar.gz
    mv nvim-linux-x86_64 /usr/local/nvim
  args:
    creates: /usr/local/nvim/bin/nvim
  vars:
    nvim_version: "0.10.4"
  become: true
