# Ansible tasks to set up Nvidia stuff
#
# apt install ubuntu-drivers-common
# sudo ubuntu-drivers install
#
# curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey     | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
#
# sudo apt-get update
#
# sudo apt install nvidia-container-toolkit nvtop

- name: Install ubuntu-drivers-common package
  apt:
    name: ubuntu-drivers-common
    state: present
  become: true

- name: check if drivers installed
  command: ubuntu-drivers list | grep nvidia
  register: drivers_installed

- name: Install recommended NVIDIA drivers
  command: ubuntu-drivers install
  become: true
  when: not drivers_installed

# curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey     | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
# curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list     | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g'     | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Add NVIDIA container toolkit GPG key
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  become: true

- name: Get NVIDIA repository list
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /tmp/nvidia-container-toolkit.list
  become: true

- name: Convert repository list to use signed-by option
  shell: sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' /tmp/nvidia-container-toolkit.list > /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install NVIDIA container toolkit and nvtop
  apt:
    name:
      - nvidia-container-toolkit
      - nvtop
    state: present
  become: true

- name: Reboot the server
  reboot:
    msg: "Rebooting the server to apply NVIDIA driver changes"
  become: true