# to bind on port 80 and 443
# setcap cap_net_bind_service=+ep $(which rootlesskit)
# systemctl --user restart containerd.service

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf.d/:/etc/nginx/conf.d
      - ~/.nginx/certs:/etc/letsencrypt
      - ~/.nginx/www:/var/www/html
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
