---
- name: Create Virtual Machines
  hosts: localhost
  vars:
    vault_password: "{{ lookup('env', 'ANSIBLE_VAULT_PASSWORD') }}"
    vm_passwords_file: "~/.homelab-passwords.yaml"
    username: steven
    github_username: sf1tzp # used to import ssh authorized_keys
    libvirt_images: /var/lib/libvirt/images/
    vm_specs:
      - hostname: devbox
        os: ubuntu-server
        vcpus: 8
        memory: 24
        ip: 10.0.0.3
        disk_size: 150G
        gpu_passthrough: false
      - hostname: llm-server
        os: ubuntu-server
        vcpus: 4
        memory: 8
        ip: 10.0.0.4
        disk_size: 150G
        gpu_passthrough: true

  tasks:
    - name: Checking if VMs exist
      virt:
        name: "{{ item.hostname }}"
        command: status
      register: vm_status
      failed_when: false
      with_items: "{{ vm_specs }}"
      loop_control:
        label: "Checking if {{ item.hostname }} is already defined"

    - set_fact:
        vms_to_create: "{{ vm_specs | selectattr('hostname', 'in', vm_status.results | selectattr('status', 'undefined') | map(attribute='item.hostname') | list) }}"

    - meta: end_play
      when: vms_to_create | length == 0

    - debug:
        msg: "Will create the following VMs: {{ vms_to_create | map(attribute='hostname') | join(', ') }}"

    - name: Generate user passwords
      include_tasks: tasks/passwords.yaml
      with_items: "{{ vms_to_create }}"
      loop_control:
        label: "Generated {{ item.hostname }} user password"

    - name: Create cloud-init image
      include_tasks: tasks/cloud-init.yaml
      with_items: "{{ vms_to_create }}"
      loop_control:
        label: "Generated {{ item.hostname }} cloud-init image"

    - name: Create OS disk images
      become: false
      shell: |
        qemu-img create \
          -F qcow2 \
          -b {{ libvirt_images }}/bases/{{ item.os }}.qcow2 \
          -f qcow2 \
          "{{ libvirt_images }}/{{ item.hostname }}.qcow2" {{ item.disk_size }}
      with_items: "{{ vms_to_create }}"
      loop_control:
        label: "Created {{ item.hostname }} OS Disk Image"

    - name: Create GPU passthrough hook directories
      become: false
      file:
        path: "/etc/libvirt/hooks/qemu.d/{{ item.0.hostname }}/{{ item.1 }}"
        state: directory
        mode: "755"
      with_nested:
        - "{{ vms_to_create }}"
        - ["prepare/begin", "release/end"]
      loop_control:
        label: "Created {{ item.0.hostname }} {{ item.1 }} hook directory"
      when: item.0.gpu_passthrough | default(false)

    - name: Render GPU passthrough hook scripts
      become: false
      template:
        src: "templates/{{ template_name }}.j2"
        dest: "/etc/libvirt/hooks/qemu.d/{{ item.0.hostname }}/{{ item.1 }}/{{ template_name }}"
        mode: "755"
      with_nested:
        - "{{ vms_to_create }}"
        - ["prepare/begin", "release/end"]
      loop_control:
        label: "Wrote {{ item.0.hostname }} hook {{ item.1 }}/{{ template_name }}"
      vars:
        template_name: "{{ 'gpu-start-hook.sh' if item.1 == 'prepare/begin' else 'gpu-stop-hook.sh' }}"
      when: item.0.gpu_passthrough | default(false)

    - name: Define virtual machines
      become: false
      virt:
        name: "{{ item.hostname }}"
        command: define
        xml: "{{ lookup('template', 'templates/vm_definition.xml.j2') }}"
      with_items: "{{ vms_to_create }}"
      loop_control:
        label: "Defined {{ item.hostname }} libvirt domain"
