---
- name: Set up machine
  hosts: all

  tasks:
    - name: Common Set Up
      include_tasks: tasks/common.yaml
      when: not inventory_hostname in groups["staging"]

    - name: Nvidia Driver Set Up
      include_tasks: tasks/nvidia.yaml
      vars:
        nvidia_gpu_exporter_version: "1.3.2"  # Override default version if needed
      when: inventory_hostname in groups["nvidia"]

    - name: Containerd (nerdctl) Set Up
      include_tasks: tasks/containerd.yaml
      vars:
        nerdctl_version: 2.1.3
      when: inventory_hostname in groups["containerd"]

    - name: Monitoring tools setup
      include_tasks: tasks/monitoring.yaml
      when: inventory_hostname in groups["monitoring"]
