
---
- name: Update VMs
  hosts: vms
  vars:

  tasks:
    - name: apt update
      apt:
        update_cache: yes
      become: true

    - name: apt ugrade
      apt:
        name: "*"
        state: latest
      become: true

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server
      reboot:
        msg: "Rebooting the server to apply NVIDIA driver changes"
      become: true
      when: reboot_required_file.stat.exists
