---
- name: Install and configure Wireguard on homelab hosts
  hosts: wireguard
  become: yes
  vars:
    vault_password: "{{ lookup('env', 'ANSIBLE_VAULT_PASSWORD') }}"
    wg_keys_file: "~/.homelab-wireguard-keys.yaml"
    wg_port: 51820
    public_endpoint: "{{ lookup('env', 'WIREGUARD_PUBLIC_ENDPOINT') }}"
  tasks:
    # Install Wireguard
    - name: Install Wireguard packages
      ansible.builtin.package:
        name:
          - wireguard-tools
          - wireguard
        state: present

    # Manage keys in the vault
    - name: Check if private keys file exists
      ansible.builtin.stat:
        path: "{{ wg_keys_file }}"
      register: keys_file
      delegate_to: localhost
      become: no

    - name: Initialize private keys file with empty structure
      ansible.builtin.copy:
        content: "wireguard:\n  private_keys: {}\n  public_keys: {}\n"
        dest: "{{ wg_keys_file }}"
        mode: "0600"
        force: false # Don't overwrite if exists
      when: not keys_file.stat.exists
      delegate_to: localhost
      become: no

    - name: Check for existing private key
      ansible.builtin.command:
        cmd: yq -e '.wireguard.private_keys.{{ inventory_hostname }}' {{ wg_keys_file }}
      register: private_key_check
      failed_when: false
      changed_when: false
      delegate_to: localhost
      become: no

    - name: Set fact if private key exists
      ansible.builtin.set_fact:
        private_key_not_set: "{{ private_key_check.rc != 0 }}" # yq failed, meaning key doesn't exist

    - name: Generate Wireguard private key
      ansible.builtin.command:
        cmd: wg genkey
      register: wg_private_key
      when: private_key_not_set
      delegate_to: localhost
      become: no

    - name: Encrypt private key
      ansible.builtin.set_fact:
        encrypted_private_key: "{{ wg_private_key.stdout | vault(vault_password) }}"
      when: private_key_not_set

    - name: Store encrypted private key in vault
      ansible.builtin.command:
        cmd: yq -i '.wireguard.private_keys.{{ inventory_hostname }} = "{{ encrypted_private_key }}"' {{ wg_keys_file }}
      when: private_key_not_set
      delegate_to: localhost
      become: no

    - name: Retrieve existing private key from vault
      ansible.builtin.command:
        cmd: yq -e '.wireguard.private_keys.{{ inventory_hostname }}' {{ wg_keys_file }}
      register: existing_private_key
      when: not private_key_not_set
      delegate_to: localhost
      become: no

    - name: Decrypt existing private key
      ansible.builtin.set_fact:
        decrypted_private_key: "{{ existing_private_key.stdout | unvault(vault_password) }}"
      when: not private_key_not_set

    - name: Set private key fact for new key
      ansible.builtin.set_fact:
        current_private_key: "{{ wg_private_key.stdout }}"
      when: private_key_not_set

    - name: Set private key fact for existing key
      ansible.builtin.set_fact:
        current_private_key: "{{ decrypted_private_key }}"
      when: not private_key_not_set

    - name: Set private key for template
      ansible.builtin.set_fact:
        private_key: "{{ current_private_key }}"

    - name: Generate public key from private key
      ansible.builtin.shell:
        cmd: echo '{{ current_private_key }}' | wg pubkey
      register: wg_public_key
      delegate_to: localhost
      become: no

    - name: Store public key (unencrypted) in vault
      ansible.builtin.command:
        cmd: yq -i '.wireguard.public_keys.{{ inventory_hostname }} = "{{ wg_public_key.stdout }}"' {{ wg_keys_file }}
      delegate_to: localhost
      become: no

    # Create a fact with all public keys for configuring peers
    - name: Get all public keys
      ansible.builtin.command:
        cmd: yq -e '.wireguard.public_keys' {{ wg_keys_file }}
      register: all_public_keys
      delegate_to: localhost
      become: no

    - name: Parse public keys
      ansible.builtin.set_fact:
        public_keys: "{{ all_public_keys.stdout | from_yaml }}"

    # Configure Wireguard
    - name: Create Wireguard configuration directory
      ansible.builtin.file:
        path: /etc/wireguard
        state: directory
        mode: "0700"

    # Create template for wg0.conf
    - name: Configure Wireguard interface
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/wg0.conf.j2"
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
      notify: restart wireguard

    # Enable and start Wireguard
    - name: Enable and start Wireguard
      ansible.builtin.service:
        name: wg-quick@wg0
        enabled: yes
        state: started

  handlers:
    - name: restart wireguard
      ansible.builtin.service:
        name: wg-quick@wg0
        state: restarted
