#ENC[AES256_GCM,data:9jBVW5b3ffgiWvHzQY2Z8JRzrR9aS5I32tN8eCfKnlGRNOW33ytiUhgwljx/9U0=,iv:Xq4n7FYCZOYDZ91H2wjwTFS3FhJpmSdcg/QCB7y07RE=,tag:ExD5WzsdyVvbJgcCZubUWA==,type:comment]
#ENC[AES256_GCM,data:FfWkGzw4CFdvmYDVaq/1/OW47yfyDu1TxHajFcbdJT9MsiC1TGd7J8x9waEnC/7f22zxzR8=,iv:Mit5e3I6VNHB8YpQda9XRV9Ww6QMY3NtidxtLGMOT0A=,tag:ElPjOIozvqi+JEcWAHfT3A==,type:comment]
#ENC[AES256_GCM,data:FCsLH5lhDLvpPOZO3/H1P/EaY0BB+6eDCBEV6mGohcySOkYJGX9j/HzHtkwxylg=,iv:j9S/HWy3CCmk9sG1hVt4sQvoNXNuSYBlpLV98W4lXYM=,tag:dlUIY9yKyUMVUycptiYFeg==,type:comment]
apiVersion: ENC[AES256_GCM,data:qrw=,iv:BOOlxGm39vl2kklEFqPiNd94uDk7ja3/Ij7Mys1YH5g=,tag:pJgxSrFOSTEJU5NXvqtRoA==,type:str]
kind: ENC[AES256_GCM,data:O1x2syIh,iv:pW2DS/kwi4HqYbAhVwKRhAYLrbb/6y5okFlHu+3TRqo=,tag:k+Cs5uHUyEADmb9TGRuXkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qEhTex+oGb/0dq0=,iv:6C42xzle+rE1uUFuORn6M+HKYzCCOxg73pv2gWG61VU=,tag:Y1LKJ6aVdnQErpNGbed/kg==,type:str]
    namespace: ENC[AES256_GCM,data:R2hXK2s=,iv:mFD1iviwjL9jX1ujinT9auoA9ITjAuUJLWG8i8cu9B4=,tag:w9ZU3W2kM2W7ZzzJOba9sg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:506nr5tuldZJ6uU=,iv:Z/b2T7YqTdNpKWuANfVAThUoMgI9sl6CEPnWVPyawCk=,tag:/WnMfoCgSsmgR4+8RgmvFg==,type:str]
    password: ENC[AES256_GCM,data:iVfiYV1WraT8vV/K3tc=,iv:ZpTm581yRzuaDap+tDrGMiv6hWFp+Q5i5PiXU4DPmeg=,tag:L8f6JMj6vwrbsE+aP6Hkrw==,type:str]
    email: ENC[AES256_GCM,data:j7UOSZXW73B/N2gLxpqfoDf2,iv:2+sbfFfDqpeAYptHaboyenK4swJFgm+oWlEpr6K4248=,tag:IN4swlZbdmmKbrYJbay5dw==,type:str]
sops:
    age:
        - recipient: age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEtLZksrMHNhT0NNQ1B1
            SU9pK2NETloxT0E2QzRCT1VjY0tscmpTUHcwCjBneXg0Z2pYVGFUeTJUYWlJOEp0
            SnhCOWRLU1FObFVLZEczdG1BZDVKeVUKLS0tIDRKOGV1SWxCcEUrVXU1WUJBbFJ5
            UEhOUGUxaVdIRzZ3TlJXem1MYmlpalEKHR9gSengD4lo1hkrKU6w/1jhepk8OZCi
            czwRxmHBc/jiVUS7/762CqOAoi2w663QB04yMFD4k26N9h9ThJektw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv7v50lygkd88nqhmy7mnxyp9jvaqmet6wdccc0zsvdjxf3t0emq4rmwrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHJQU0hrUGRyWi9KSWlG
            ZlEwcjVKNU03ZjZJYkh1Tmw0Z3Rpa05IcURjCmN5MWhHWi9Bdzg0Y0JXejBxNEht
            dVM4a3NiTlVkOHM2eTFCOHY3ckNMZjgKLS0tIEdOMmhWY0wwb2w4Z2pXZWE4RlhM
            K1ZxeitmQUlKWDc2SHh3R3hpbS9HQlUKZalymepGMznxkhpoaq0F2bLNsIUOJ6A7
            fmrzwT1KoPxEkOPyCZlIthV29DsIVUJ2CECo4LhLTC4BFUbCP+7QxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s59a0sgvuqutt9kyck3cz347g0mlzgrjg6z3ushzyp2jxy5h9gnqsjfj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcHRGaURZdCtMcjh6US9D
            MzQ2L3pOWTNOY05RaUlic0locERHeUtJQkJJCmhySXZMK3FZaElyMnZmN0V1TlhD
            MHNGcWdjaGxiQXFWRmtlbCszblJWaU0KLS0tIHR6eHJsTkxzdDlaUFRHZU9ieW1h
            dEo4T05ZUStFOWxVV1ZZS01xRm12VVEKdG3XrnhU25JnQPFic7cIxlKfB9SezN13
            wMQxFvfPxixslGFTGw7ek1BWkJ+7tqpW/XEIk9d00VM8q3Hg9jOQgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7umu2tev8057x4qte4g8smua7nqhdhqmrk49pq9xpx6zxc0p3qjurnlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrckxsbkh6TDY0MCtaNmhO
            MUFLN0tZSWdGY2RVRkJEaW5Xb3FWYVQ1M1VJClBheDV4K3p3Ty9qaU1Qa25CVVlz
            ektNUVRDNnJRL3NVV3dPdFhsbENSQ3cKLS0tIGRYWjhQZkVVclM1RzJKUnhQSFJn
            RFpyc2dXcXhDVVJHZ1RsMDNDNC91V3MKGK0vpboxn60URRoDthfPswCcxf4xjjzt
            fOPsPlXRJFvwK32EXI33IgufklTLkc8KARlzbLm9eXlEhk+m9J4xSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:18:12Z"
    mac: ENC[AES256_GCM,data:GztUPwpoGG9mRhNs04tf7z4CBXo25rIf8eZWN4gIx/37gJBetXB8obhYR4LPkcSPezsiRjmYtVcoD+Go+k6iy5nybnbXHBheDl9y1+eXDRA0tWfG4/KZS0J7kXPzHnSqdyr3MZ8fN/br/tfY/cotMa36Nip1BpGBqCje7SkVEPk=,iv:ZdWkvAzpp/i4OEK+L8gje6vB6KZMARMJTZQSxy6/RXk=,tag:scwFzc7TUFwknJp6EOrzcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:qrw=,iv:BOOlxGm39vl2kklEFqPiNd94uDk7ja3/Ij7Mys1YH5g=,tag:pJgxSrFOSTEJU5NXvqtRoA==,type:str]
kind: ENC[AES256_GCM,data:O1x2syIh,iv:pW2DS/kwi4HqYbAhVwKRhAYLrbb/6y5okFlHu+3TRqo=,tag:k+Cs5uHUyEADmb9TGRuXkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mU25QU2iLNTG6Nag6iSBYIJJ1ok=,iv:MVIHNBYoXFdIGT2YkDnnaRSirNit6yBdr3lJew+ZBzE=,tag:0crDxgZ4R5OHhcciVqkWzg==,type:str]
    namespace: ENC[AES256_GCM,data:R2hXK2s=,iv:mFD1iviwjL9jX1ujinT9auoA9ITjAuUJLWG8i8cu9B4=,tag:w9ZU3W2kM2W7ZzzJOba9sg==,type:str]
stringData:
    #ENC[AES256_GCM,data:6jD8N7H4x41SJMFyrXV/SZTk/hbG3tEQx+rqSkQ0C/VTe7EcgSnS/tE=,iv:Hwg7PCKmTTNyKLGbktKh2wkdueCWfOLvbVsMCdrBymE=,tag:93AiZUQUDBzOSOceryFm3A==,type:comment]
    password: ENC[AES256_GCM,data:tVSfdBdRPBG79sQ9uiM=,iv:Cj4ltrJsr/R6Yj6WnmEsy+VTrg3wEvsF831xPgNb73A=,tag:uBLI6QW6SZt+/x6S1gzt2A==,type:str]
sops:
    age:
        - recipient: age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEtLZksrMHNhT0NNQ1B1
            SU9pK2NETloxT0E2QzRCT1VjY0tscmpTUHcwCjBneXg0Z2pYVGFUeTJUYWlJOEp0
            SnhCOWRLU1FObFVLZEczdG1BZDVKeVUKLS0tIDRKOGV1SWxCcEUrVXU1WUJBbFJ5
            UEhOUGUxaVdIRzZ3TlJXem1MYmlpalEKHR9gSengD4lo1hkrKU6w/1jhepk8OZCi
            czwRxmHBc/jiVUS7/762CqOAoi2w663QB04yMFD4k26N9h9ThJektw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv7v50lygkd88nqhmy7mnxyp9jvaqmet6wdccc0zsvdjxf3t0emq4rmwrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHJQU0hrUGRyWi9KSWlG
            ZlEwcjVKNU03ZjZJYkh1Tmw0Z3Rpa05IcURjCmN5MWhHWi9Bdzg0Y0JXejBxNEht
            dVM4a3NiTlVkOHM2eTFCOHY3ckNMZjgKLS0tIEdOMmhWY0wwb2w4Z2pXZWE4RlhM
            K1ZxeitmQUlKWDc2SHh3R3hpbS9HQlUKZalymepGMznxkhpoaq0F2bLNsIUOJ6A7
            fmrzwT1KoPxEkOPyCZlIthV29DsIVUJ2CECo4LhLTC4BFUbCP+7QxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s59a0sgvuqutt9kyck3cz347g0mlzgrjg6z3ushzyp2jxy5h9gnqsjfj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcHRGaURZdCtMcjh6US9D
            MzQ2L3pOWTNOY05RaUlic0locERHeUtJQkJJCmhySXZMK3FZaElyMnZmN0V1TlhD
            MHNGcWdjaGxiQXFWRmtlbCszblJWaU0KLS0tIHR6eHJsTkxzdDlaUFRHZU9ieW1h
            dEo4T05ZUStFOWxVV1ZZS01xRm12VVEKdG3XrnhU25JnQPFic7cIxlKfB9SezN13
            wMQxFvfPxixslGFTGw7ek1BWkJ+7tqpW/XEIk9d00VM8q3Hg9jOQgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7umu2tev8057x4qte4g8smua7nqhdhqmrk49pq9xpx6zxc0p3qjurnlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrckxsbkh6TDY0MCtaNmhO
            MUFLN0tZSWdGY2RVRkJEaW5Xb3FWYVQ1M1VJClBheDV4K3p3Ty9qaU1Qa25CVVlz
            ektNUVRDNnJRL3NVV3dPdFhsbENSQ3cKLS0tIGRYWjhQZkVVclM1RzJKUnhQSFJn
            RFpyc2dXcXhDVVJHZ1RsMDNDNC91V3MKGK0vpboxn60URRoDthfPswCcxf4xjjzt
            fOPsPlXRJFvwK32EXI33IgufklTLkc8KARlzbLm9eXlEhk+m9J4xSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:18:12Z"
    mac: ENC[AES256_GCM,data:GztUPwpoGG9mRhNs04tf7z4CBXo25rIf8eZWN4gIx/37gJBetXB8obhYR4LPkcSPezsiRjmYtVcoD+Go+k6iy5nybnbXHBheDl9y1+eXDRA0tWfG4/KZS0J7kXPzHnSqdyr3MZ8fN/br/tfY/cotMa36Nip1BpGBqCje7SkVEPk=,iv:ZdWkvAzpp/i4OEK+L8gje6vB6KZMARMJTZQSxy6/RXk=,tag:scwFzc7TUFwknJp6EOrzcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
