#ENC[AES256_GCM,data:9jBVW5b3ffgiWvHzQY2Z8JRzrR9aS5I32tN8eCfKnlGRNOW33ytiUhgwljx/9U0=,iv:Xq4n7FYCZOYDZ91H2wjwTFS3FhJpmSdcg/QCB7y07RE=,tag:ExD5WzsdyVvbJgcCZubUWA==,type:comment]
#ENC[AES256_GCM,data:FfWkGzw4CFdvmYDVaq/1/OW47yfyDu1TxHajFcbdJT9MsiC1TGd7J8x9waEnC/7f22zxzR8=,iv:Mit5e3I6VNHB8YpQda9XRV9Ww6QMY3NtidxtLGMOT0A=,tag:ElPjOIozvqi+JEcWAHfT3A==,type:comment]
#ENC[AES256_GCM,data:FCsLH5lhDLvpPOZO3/H1P/EaY0BB+6eDCBEV6mGohcySOkYJGX9j/HzHtkwxylg=,iv:j9S/HWy3CCmk9sG1hVt4sQvoNXNuSYBlpLV98W4lXYM=,tag:dlUIY9yKyUMVUycptiYFeg==,type:comment]
apiVersion: ENC[AES256_GCM,data:qrw=,iv:BOOlxGm39vl2kklEFqPiNd94uDk7ja3/Ij7Mys1YH5g=,tag:pJgxSrFOSTEJU5NXvqtRoA==,type:str]
kind: ENC[AES256_GCM,data:O1x2syIh,iv:pW2DS/kwi4HqYbAhVwKRhAYLrbb/6y5okFlHu+3TRqo=,tag:k+Cs5uHUyEADmb9TGRuXkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qEhTex+oGb/0dq0=,iv:6C42xzle+rE1uUFuORn6M+HKYzCCOxg73pv2gWG61VU=,tag:Y1LKJ6aVdnQErpNGbed/kg==,type:str]
    namespace: ENC[AES256_GCM,data:R2hXK2s=,iv:mFD1iviwjL9jX1ujinT9auoA9ITjAuUJLWG8i8cu9B4=,tag:w9ZU3W2kM2W7ZzzJOba9sg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:4Aqu6Cqr,iv:XCqMLfU4yMjt4OtBwhtYAxuy1UQSHmyc/U4Kl28Z7vU=,tag:qjz6yrRrNx/NkmXzdf91kw==,type:str]
    password: ENC[AES256_GCM,data:oku/NtWeOCI/M45wN+FFM3qwPY8fLhA=,iv:EWJyfPyOFXht76FskozBUvnSpeP16RO04yFyD7rM5MM=,tag:gEvWnNyVQ7codiAaTySXLQ==,type:str]
    email: ENC[AES256_GCM,data:mvJVXOnTGWRbBmXSnPo=,iv:Zv6Gj6S42Ds+x8VaDJtnEaERfPxfZSc9dU5YZQs2OnE=,tag:pCZfOEbIAeWNyVMeGw5rsg==,type:str]
sops:
    age:
        - recipient: age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEtLZksrMHNhT0NNQ1B1
            SU9pK2NETloxT0E2QzRCT1VjY0tscmpTUHcwCjBneXg0Z2pYVGFUeTJUYWlJOEp0
            SnhCOWRLU1FObFVLZEczdG1BZDVKeVUKLS0tIDRKOGV1SWxCcEUrVXU1WUJBbFJ5
            UEhOUGUxaVdIRzZ3TlJXem1MYmlpalEKHR9gSengD4lo1hkrKU6w/1jhepk8OZCi
            czwRxmHBc/jiVUS7/762CqOAoi2w663QB04yMFD4k26N9h9ThJektw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv7v50lygkd88nqhmy7mnxyp9jvaqmet6wdccc0zsvdjxf3t0emq4rmwrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHJQU0hrUGRyWi9KSWlG
            ZlEwcjVKNU03ZjZJYkh1Tmw0Z3Rpa05IcURjCmN5MWhHWi9Bdzg0Y0JXejBxNEht
            dVM4a3NiTlVkOHM2eTFCOHY3ckNMZjgKLS0tIEdOMmhWY0wwb2w4Z2pXZWE4RlhM
            K1ZxeitmQUlKWDc2SHh3R3hpbS9HQlUKZalymepGMznxkhpoaq0F2bLNsIUOJ6A7
            fmrzwT1KoPxEkOPyCZlIthV29DsIVUJ2CECo4LhLTC4BFUbCP+7QxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s59a0sgvuqutt9kyck3cz347g0mlzgrjg6z3ushzyp2jxy5h9gnqsjfj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcHRGaURZdCtMcjh6US9D
            MzQ2L3pOWTNOY05RaUlic0locERHeUtJQkJJCmhySXZMK3FZaElyMnZmN0V1TlhD
            MHNGcWdjaGxiQXFWRmtlbCszblJWaU0KLS0tIHR6eHJsTkxzdDlaUFRHZU9ieW1h
            dEo4T05ZUStFOWxVV1ZZS01xRm12VVEKdG3XrnhU25JnQPFic7cIxlKfB9SezN13
            wMQxFvfPxixslGFTGw7ek1BWkJ+7tqpW/XEIk9d00VM8q3Hg9jOQgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7umu2tev8057x4qte4g8smua7nqhdhqmrk49pq9xpx6zxc0p3qjurnlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrckxsbkh6TDY0MCtaNmhO
            MUFLN0tZSWdGY2RVRkJEaW5Xb3FWYVQ1M1VJClBheDV4K3p3Ty9qaU1Qa25CVVlz
            ektNUVRDNnJRL3NVV3dPdFhsbENSQ3cKLS0tIGRYWjhQZkVVclM1RzJKUnhQSFJn
            RFpyc2dXcXhDVVJHZ1RsMDNDNC91V3MKGK0vpboxn60URRoDthfPswCcxf4xjjzt
            fOPsPlXRJFvwK32EXI33IgufklTLkc8KARlzbLm9eXlEhk+m9J4xSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T21:08:03Z"
    mac: ENC[AES256_GCM,data:g76ejoVYdqo53fZ/duO0t50ZHmfIiv/YrWN0kuSwSQy3szKJQI5QJALCif+z4vzq+pVpgjdRQ7kLlkfUVJI8cKO2eGSkGvC/5w6N3xsRZ5o7tQWrQsKakvXtesY2QRk9lkpxNqSVgVU6nLU2S+c3V05p9KfLse5VOk6w6vhG4wE=,iv:wRqlkTZT4FQ2g50EIdgUIbx9+RNjVUtRr90Lnyw7LAs=,tag:f+oVuqgyiigUYyiQL9x2MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:qrw=,iv:BOOlxGm39vl2kklEFqPiNd94uDk7ja3/Ij7Mys1YH5g=,tag:pJgxSrFOSTEJU5NXvqtRoA==,type:str]
kind: ENC[AES256_GCM,data:O1x2syIh,iv:pW2DS/kwi4HqYbAhVwKRhAYLrbb/6y5okFlHu+3TRqo=,tag:k+Cs5uHUyEADmb9TGRuXkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mU25QU2iLNTG6Nag6iSBYIJJ1ok=,iv:MVIHNBYoXFdIGT2YkDnnaRSirNit6yBdr3lJew+ZBzE=,tag:0crDxgZ4R5OHhcciVqkWzg==,type:str]
    namespace: ENC[AES256_GCM,data:R2hXK2s=,iv:mFD1iviwjL9jX1ujinT9auoA9ITjAuUJLWG8i8cu9B4=,tag:w9ZU3W2kM2W7ZzzJOba9sg==,type:str]
stringData:
    #ENC[AES256_GCM,data:iShW5XvjdOhJNRmGMizhcH3POZreZsiuyJ+8iaMlEgMUmGPpnhqxlX1KD22D/q/RtSc=,iv:/bVKIqxkZ//dmKaZJPYDHOdGtU5AB2JAFTQ9Qv5zKC0=,tag:/PkqMG5opcyaFIgwX4Vc4g==,type:comment]
    password: ENC[AES256_GCM,data:oYpkHiCYBmhuckQfKH8WvJXVaJ35QQYD/MxSH7ePqEtwk3fvy2JMnRH58cRgQh5QvKq0tbwM6H8p18eJXIyNdw==,iv:RHA9HjVl/Ai+mv8tkExifv9NGFi4c/acP6wx4QWuHV8=,tag:5Sak5rag6ufUmi2t4puFMA==,type:str]
sops:
    age:
        - recipient: age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEtLZksrMHNhT0NNQ1B1
            SU9pK2NETloxT0E2QzRCT1VjY0tscmpTUHcwCjBneXg0Z2pYVGFUeTJUYWlJOEp0
            SnhCOWRLU1FObFVLZEczdG1BZDVKeVUKLS0tIDRKOGV1SWxCcEUrVXU1WUJBbFJ5
            UEhOUGUxaVdIRzZ3TlJXem1MYmlpalEKHR9gSengD4lo1hkrKU6w/1jhepk8OZCi
            czwRxmHBc/jiVUS7/762CqOAoi2w663QB04yMFD4k26N9h9ThJektw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vv7v50lygkd88nqhmy7mnxyp9jvaqmet6wdccc0zsvdjxf3t0emq4rmwrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHJQU0hrUGRyWi9KSWlG
            ZlEwcjVKNU03ZjZJYkh1Tmw0Z3Rpa05IcURjCmN5MWhHWi9Bdzg0Y0JXejBxNEht
            dVM4a3NiTlVkOHM2eTFCOHY3ckNMZjgKLS0tIEdOMmhWY0wwb2w4Z2pXZWE4RlhM
            K1ZxeitmQUlKWDc2SHh3R3hpbS9HQlUKZalymepGMznxkhpoaq0F2bLNsIUOJ6A7
            fmrzwT1KoPxEkOPyCZlIthV29DsIVUJ2CECo4LhLTC4BFUbCP+7QxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s59a0sgvuqutt9kyck3cz347g0mlzgrjg6z3ushzyp2jxy5h9gnqsjfj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcHRGaURZdCtMcjh6US9D
            MzQ2L3pOWTNOY05RaUlic0locERHeUtJQkJJCmhySXZMK3FZaElyMnZmN0V1TlhD
            MHNGcWdjaGxiQXFWRmtlbCszblJWaU0KLS0tIHR6eHJsTkxzdDlaUFRHZU9ieW1h
            dEo4T05ZUStFOWxVV1ZZS01xRm12VVEKdG3XrnhU25JnQPFic7cIxlKfB9SezN13
            wMQxFvfPxixslGFTGw7ek1BWkJ+7tqpW/XEIk9d00VM8q3Hg9jOQgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qg7umu2tev8057x4qte4g8smua7nqhdhqmrk49pq9xpx6zxc0p3qjurnlh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrckxsbkh6TDY0MCtaNmhO
            MUFLN0tZSWdGY2RVRkJEaW5Xb3FWYVQ1M1VJClBheDV4K3p3Ty9qaU1Qa25CVVlz
            ektNUVRDNnJRL3NVV3dPdFhsbENSQ3cKLS0tIGRYWjhQZkVVclM1RzJKUnhQSFJn
            RFpyc2dXcXhDVVJHZ1RsMDNDNC91V3MKGK0vpboxn60URRoDthfPswCcxf4xjjzt
            fOPsPlXRJFvwK32EXI33IgufklTLkc8KARlzbLm9eXlEhk+m9J4xSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T21:08:03Z"
    mac: ENC[AES256_GCM,data:g76ejoVYdqo53fZ/duO0t50ZHmfIiv/YrWN0kuSwSQy3szKJQI5QJALCif+z4vzq+pVpgjdRQ7kLlkfUVJI8cKO2eGSkGvC/5w6N3xsRZ5o7tQWrQsKakvXtesY2QRk9lkpxNqSVgVU6nLU2S+c3V05p9KfLse5VOk6w6vhG4wE=,iv:wRqlkTZT4FQ2g50EIdgUIbx9+RNjVUtRr90Lnyw7LAs=,tag:f+oVuqgyiigUYyiQL9x2MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
