up:
    nerdctl compose -f staging-proxy-compose.yaml up -d

down:
    nerdctl compose -f staging-proxy-compose.yaml down

logs *ARGS:
    nerdctl compose -f staging-proxy-compose.yaml logs {{ARGS}}

reload:
    nerdctl exec -it staging-proxy -- caddy reload --config /etc/caddy/Caddyfile
