# docker compose file for nginx
# load config from './nginx.conf'
#
services:
  nginx:
    image: nginx:latest
    container_name: lab-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
