- name: Decrypt VM Password
  hosts: localhost
  vars:
    vault_password: "{{ lookup('env', 'ANSIBLE_VAULT_PASSWORD') }}"
    vm_passwords_file: "~/.homelab-passwords.yaml"
  vars_prompt:
    - name: vm_name
      prompt: "Which VM do you want the password for?"
      private: no
  tasks:
    - name: Open vault file
      include_vars:
        file: "{{ vm_passwords_file }}"
        name: vault

    - name: Get cyphertext
      set_fact:
        cyphertext: "{{ vault.vms[vm_name].user_password }}"

    - name: Decrypt cyphertext
      set_fact:
        decrypted: "{{ cyphertext | unvault(vault_password) }}"

    - name: Log decrypted plaintext
      debug:
        msg: "{{ decrypted }}"
