start vm:
    virsh start {{vm}}

create-vms:
    ansible-playbook virtual-machines.yaml --vault-password-file ~/.ansible-password

decrypt-vm-password:
    ansible-playbook decrypt-vm-password.yaml --vault-password-file ~/.ansible-password

delete-vitrual-machines:
    ansible-playbook delete-virtual-machines.yaml

create-base-images:
    ansible-playbook create-base-images.yaml

_base_images_from_iso:
    #!/bin/bash
    set -ex
    pushd /var/lib/libvirt/images
    qemu-img convert -f raw ubuntu-24.04.2-live-server-amd64.iso 	-O qcow2 ubuntu-base.qcow2
    qemu-img convert -f raw ubuntu-24.04.2-desktop-amd64.iso 	-O qcow2 ubuntu-desktop-base.qcow2
    qemu-img convert -f raw latest-nixos-minimal-x86_64-linux.iso 	-O qcow2 nixos-base.qcow2
    popd

