up:
    nerdctl compose -f ~/.files/homelab/services/ollama-chat/ollama.yaml up -d

down:
    nerdctl compose -f ~/.files/homelab/services/ollama-chat/ollama.yaml down

logs:
    nerdctl compose -f ollama.yaml logs -f