up:
    nerdctl compose -f ollama.yaml up -d

down:
    nerdctl compose -f ollama.yaml down

logs *ARGS:
    nerdctl compose -f ollama.yaml logs {{ARGS}}

filtered-ollama-logs:
    just logs ollama -f | grep -v '/api/ps' | grep -v '"/"'

update: down
    nerdctl image rm ghcr.io/open-webui/open-webui:main
    nerdctl image rm ollama/ollama:latest


