services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      OLLAMA_HOST: 0.0.0.0:${OLLAMA_PORT:-11434}
      OLLAMA_ORIGINS: "https://chat.lofi/*,http://10.0.0.*"
    ports:
      - ${OLLAMA_PORT:-11434}:11434
    volumes:
      - ${OLLAMA_MODELS:-$HOME/.ollama/models}:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all # allow ollama to use all GPUs

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      WEBUI_AUTH: "False"
      ENABLE_SIGNUP: "False"
      OLLAMA_BASE_URL: http://10.0.0.4:${OLLAMA_PORT:-11434}
    ports:
      - ${OPEN_WEBUI_PORT:-3000}:8080
    volumes:
      - ${OPEN_WEBUI_DATA:-$HOME/.open-webui/data}:/app/backend/data
