{
 "title": "K8s Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "k8s_node",
    "query": {
     "query": "query_result(up{job=\"k8s\"} == 1)"
    }
   },
   {
    "name": "pod_controllers",
    "query": {
     "query": "label_values(kube_pod_info,created_by_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Utilization ($k8s_node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "k8s_node" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$k8s_node\"}[$__rate_interval])) * 100)",
     "legendFormat": "Core {{cpu}}"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$k8s_node\", chip=\"0000:00:08_1_0000:73:00_0\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "node_power_supply_capacity{instance=\"$k8s_node\",power_supply=\"BAT0\"}",
     "legendFormat": "battery_level"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$k8s_node\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$k8s_node\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$k8s_node\",device=~\"br0|enp0s5\"}[$__rate_interval]) * 8",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$k8s_node\",device=~\"br0|enp0s5\"}[$__rate_interval]) * 8",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$k8s_node\",mountpoint=\"/\"} - node_filesystem_free_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$k8s_node\",mountpoint=\"/\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$k8s_node\",mountpoint=\"/var\"}  - node_filesystem_free_bytes",
     "legendFormat": "var-used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$k8s_node\",mountpoint=\"/var\"}",
     "legendFormat": "var-total"
    }
   ]
  },
  { "title": "Container Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": " rate(container_cpu_usage_seconds_total{container!~\"\"}[5m])\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info",
     "legendFormat": "{{container}} {{pod}} CPU Usage"
    },
    {
     "expr": " sum(rate(container_cpu_usage_seconds_total{container!~\"\"}[5m])\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info)",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!~\"\"}\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info",
     "legendFormat": "{{container}} {{pod}} Usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!~\"\"}\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info)",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "${pod_controllers}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "pod_controllers",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": " rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info{created_by_name=\"$pod_controllers\"}",
       "legendFormat": "{{container}} {{pod}} CPU Usage"
      },
      {
       "expr": " kube_pod_container_resource_limits{resource=\"cpu\"}\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info{created_by_name=\"$pod_controllers\"}",
       "legendFormat": "{{container}} {{pod}} CPU Limit"
      }
     ]
    },
    {
     "title": "Container Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\"}\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info{created_by_name=\"$pod_controllers\"}",
       "legendFormat": "{{container}} {{pod}} Usage"
      },
      {
       "expr": " kube_pod_container_resource_limits{resource=\"memory\"}\n * on(namespace, pod) group_left(created_by_name)\n kube_pod_info{created_by_name=\"$pod_controllers\"}\n",
       "legendFormat": "{{container}} {{pod}} Limit"
      }
     ]
    }
   ]
  }
 ]
}