{
 "title": "lofi lab",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "gpu_id",
    "query": {
     "query": "label_values(nvidia_smi_index,uuid)"
    }
   },
   {
    "name": "linux_vm",
    "query": {
     "query": "query_result(up{job=\"linux_vms\"} == 1)"
    }
   },
   {
    "name": "staging_vm",
    "query": {
     "query": "query_result(up{job=\"staging\"} == 1)"
    }
   },
   {
    "name": "windows_vm",
    "query": {
     "query": "query_result(up{job=\"windows_exporter\"})"
    }
   },
   {
    "name": "macs",
    "query": {
     "query": "query_result(up{job=\"macs\"} == 1)"
    }
   },
   {
    "name": "mac_ethernet",
    "query": {
     "query": "label_values(node_network_transmit_bytes_total{instance=\"$macs\"},ethernet_device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Audit Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "count by(host) (rate({job=\"audit\"} | action =~ `USER_ERR|USER_LOGIN` [$__auto]))",
       "legendFormat": "{{.host}}"
      }
     ]
    },
    {
     "title": "User Logins",
     "type": "logs",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"audit\"} | action =~ `USER_ERR|USER_LOGIN`",
       "legendFormat": "{{.host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"router\"}[5m])) * 100)",
       "legendFormat": "Core {{cpu}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"router\",job=\"linux_baremetal\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"router\",job=\"linux_baremetal\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "WAN Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"router\",device=~\"eth1\"}[$__rate_interval]) * 8",
       "legendFormat": "Tx"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"router\",device=~\"eth1\"}[$__rate_interval]) * 8",
       "legendFormat": "Rx"
      }
     ]
    },
    {
     "title": "Upstream Connectivity",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 2 },
     "targets": [
      {
       "expr": "sum(probe_success{job=\"http_from_router\"})",
       "legendFormat": "Status"
      }
     ]
    }
   ]
  },
  { "title": "hypervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"soundship\"}[$__rate_interval])) * 100",
     "legendFormat": "Core {{cpu}}"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=\"soundship\"}[$__rate_interval])) * 100)",
     "legendFormat": "all_cpu"
    },
    {
     "expr": "node_hwmon_temp_celsius{chip=\"0000:00:08_1_0000:0d:00_0\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"soundship\",job=\"linux_baremetal\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"soundship\",job=\"linux_baremetal\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Hugepage Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(1 - node_memory_HugePages_Free{instance=\"soundship\", job=\"linux_baremetal\"} / node_memory_HugePages_Total{instance=\"soundship\", job=\"linux_baremetal\"}) * node_memory_HugePages_Total * 2",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"soundship\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"soundship\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"soundship\",mountpoint=\"/\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu_id\"}",
     "legendFormat": "compute ({{instance}})"
    },
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu_id\"}",
     "legendFormat": "vram"
    },
    {
     "expr": "nvidia_smi_fan_speed_ratio{uuid=\"$gpu_id\"}",
     "legendFormat": "fan_speed"
    },
    {
     "expr": "nvidia_smi_temperature_gpu{instance=\"llm-server\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"soundship\",device=\"eno1\"}[$__rate_interval]) * 8",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"soundship\",device=\"eno1\"}[$__rate_interval]) * 8",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Upstream Connectivity",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"https_from_soundship\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "$windows_vm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "windows_vm",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (core) (irate(windows_cpu_time_total{mode=\"idle\", instance=\"$windows_vm\"}[$__rate_interval])) * 100)",
       "legendFormat": "Core [{{core}}]"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_memory_physical_total_bytes{instance=\"$windows_vm\"} - windows_memory_physical_free_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "windows_memory_physical_total_bytes{instance=\"$windows_vm\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(windows_net_bytes_sent_total{instance=\"$windows_vm\"}[$__rate_interval]) * 8",
       "legendFormat": "Tx {{device}} "
      },
      {
       "expr": "rate(windows_net_bytes_received_total{instance=\"$windows_vm\"}[$__rate_interval]) * 8",
       "legendFormat": "Rx {{device}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(windows_logical_disk_size_bytes{instance=\"$windows_vm\",volume!~\"HarddiskVolume.*\"} - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$macs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "macs",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$macs\"}[$__rate_interval])) * 100)",
       "legendFormat": "Core {{cpu}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_active_bytes{instance=\"$macs\"} * 1.3 + node_memory_wired_bytes + node_memory_compressed_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_total_bytes{instance=\"$macs\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$macs\"}[$__rate_interval]) * 8",
       "legendFormat": "Tx"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$macs\"}[$__rate_interval]) * 8",
       "legendFormat": "Rx"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$macs\",mountpoint=\"/\"} - node_filesystem_free_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=\"$macs\",mountpoint=\"/\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "ollama",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Model Performance Summary",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2358 },
     "targets": [
      {
       "expr": "sum by (model) (ollama_requests_total)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (model) (ollama_response_seconds_sum) / sum by (model) (ollama_response_seconds_count)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (model) (ollama_tokens_per_second_sum) / sum by (model) (ollama_tokens_per_second_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Count of responses by Token/s",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 2358 },
     "targets": [
      {
       "expr": "ollama_tokens_per_second_bucket",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2365 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu_id\", instance=\"llm-server\"}",
       "legendFormat": "compute ({{instance}})"
      },
      {
       "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu_id\", instance=\"llm-server\"}",
       "legendFormat": "vram"
      },
      {
       "expr": "nvidia_smi_fan_speed_ratio{uuid=\"$gpu_id\", instance=\"llm-server\"}",
       "legendFormat": "fan_speed"
      },
      {
       "expr": "nvidia_smi_temperature_gpu{instance=\"llm-server\"}",
       "legendFormat": "temperature"
      }
     ]
    },
    {
     "title": "Tokens Generated Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2367 },
     "targets": [
      {
       "expr": "sum by (model) (rate(ollama_tokens_generated_total[5m]))",
       "legendFormat": "{{model}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$linux_vm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "linux_vm",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$linux_vm\"}[$__rate_interval])) * 100)",
       "legendFormat": "Core {{cpu}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 11, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$linux_vm\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$linux_vm\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$linux_vm\",device=\"ens3\"}[$__rate_interval]) * 8",
       "legendFormat": "Tx"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$linux_vm\",device=\"ens3\"}[$__rate_interval]) * 8",
       "legendFormat": "Rx"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$linux_vm\",mountpoint=\"/\"} - node_filesystem_free_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=\"$linux_vm\",mountpoint=\"/\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "$staging_vm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "staging_vm",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$staging_vm\"}[$__rate_interval])) * 100)",
       "legendFormat": "Core {{cpu}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 11, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$staging_vm\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$staging_vm\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$staging_vm\",device=\"ens3\"}[$__rate_interval]) * 8",
       "legendFormat": "Tx"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$staging_vm\",device=\"ens3\"}[$__rate_interval]) * 8",
       "legendFormat": "Rx"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$staging_vm\",mountpoint=\"/\"} - node_filesystem_free_bytes",
       "legendFormat": "used"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=\"$staging_vm\",mountpoint=\"/\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}