{
 "title": "fitz.gg",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "linux_vm",
    "query": {
     "query": "query_result(up{job=\"linux_vms\", instance=~\"staging.*\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "2m HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{host=~\".*fitz.gg|streetfortress.com|symbology.online\",server=~\"srv.*\"}[2m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "p95 Request Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(caddy_http_request_duration_seconds_bucket{host=~\".*fitz.gg|streetfortress.com|symbology.online\",server=~'srv.*'}) by (le,host)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu, instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\".*.streetfortress.cloud\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{instance}} Core {{cpu}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\".*.streetfortress.cloud\"}[$__rate_interval ])) * 100)",
     "legendFormat": "all_cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*streetfortress.cloud\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*streetfortress.cloud\"}",
     "legendFormat": "{{instance}} total"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"web2.streetfortress.cloud\",device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"web2.streetfortress.cloud\",device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://.*fitz.gg|streetfortress.com|symbology.online\", job=\"https_from_soundship\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "count by(host) (rate({job=\"audit\", host=~\".*.streetfortress.cloud\"} | action =~ `USER_ERR|USER_LOGIN` [$__auto]))",
       "legendFormat": "{{.host}}"
      }
     ]
    },
    {
     "title": "User Logins",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"audit\", host=~\".*.streetfortress.cloud\"} | action =~ `USER_ERR|USER_LOGIN`",
       "legendFormat": "{{.host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "fitz.gg API Log Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 25 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"fitz.gg-api\", host=\"fitz.gg-production\"} != \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"{{.host}} {{.level}} {{.caller}} {{.function}}\"[$__auto]))",
       "legendFormat": "api {{level}}"
      },
      {
       "direction": "backward",
       "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"fitz.gg-api\", host=\"fitz.gg-production\"} |= \"log_client_message\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))",
       "legendFormat": "ui {{level}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\".*.streetfortress.cloud\",mountpoint=\"/\"} - node_filesystem_free_bytes",
       "legendFormat": "{{instance}} used"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=~\".*.streetfortress.cloud\",mountpoint=\"/\"}",
       "legendFormat": "{{instance}} total"
      }
     ]
    },
    {
     "title": "fitz.gg API",
     "type": "logs",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 33 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"container\", container_name=\"fitz.gg-api\", host=\"fitz.gg-production\"} != \"uvicorn\" != \"log_client_message\"| json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"api {{.level}} {{.caller}}\\t{{.function}}\\t{{.event}}\"",
       "legendFormat": "fitz.gg-api"
      }
     ]
    },
    {
     "title": "Nginx & Uvicorn Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 41 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (detected_level) (count_over_time({job=\"container\", container_name=\"fitz.gg-ui\", host=\"fitz.gg-production\"} | json | line_format \"{{.log}}\" | json log | line_format \"{{.timestamp}}\\t{{.level}}\\t{{.log}}\"[$__auto]))",
       "legendFormat": "{{detected_level}}"
      },
      {
       "direction": "backward",
       "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"fitz.gg-api\", host=\"fitz.gg-production\"} |= \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))"
      }
     ]
    },
    {
     "title": "Nginx & Uvicorn Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 49 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"container\", container_name=\"fitz.gg-ui\", host=\"fitz.gg-production\"} | json | line_format \"{{.log}}\" | json log | line_format \"ui nginx\\t{{.detected_level}}\\t{{.log}}\"",
       "legendFormat": "fitz.gg-api"
      },
      {
       "direction": "backward",
       "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"fitz.gg-api\", host=\"fitz.gg-production\"} |= \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))"
      }
     ]
    }
   ]
  }
 ]
}