{
 "title": "Symbology",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "linux_vm",
    "query": {
     "query": "query_result(up{job=\"linux_vms\", instance=~\"staging.*\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Audit Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "count by(host) (rate({job=\"audit\", host=~\"symbology-production|staging.*\"} | action =~ `USER_ERR|USER_LOGIN` [$__auto]))",
       "legendFormat": "{{.host}}"
      }
     ]
    },
    {
     "title": "User Logins",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"audit\", host=~\"symbology-production|staging.*\"} | action =~ `USER_ERR|USER_LOGIN`",
       "legendFormat": "{{.host}}"
      }
     ]
    }
   ]
  },
  { "title": "production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://symbology.online\", job=\"https_from_soundship\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"symbology-production\"}[$__rate_interval])) * 100)",
     "legendFormat": "Core {{cpu}}"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=\"symbology-production\"}[$__rate_interval ])) * 100)",
     "legendFormat": "all_cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"symbology-production\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"symbology-production\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"symbology-production\",device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"symbology-production\",device=\"eth0\"}[$__rate_interval]) * 8",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Symbology API Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"symbology-api\", host=\"symbology-production\"} != \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"{{.host}} {{.level}} {{.caller}} {{.function}}\"[$__auto]))",
     "legendFormat": "api {{level}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"symbology-api\", host=\"symbology-production\"} |= \"log_client_message\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))",
     "legendFormat": "ui {{level}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"symbology-production\",mountpoint=\"/\"} - node_filesystem_free_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"symbology-production\",mountpoint=\"/\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Symbology API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"container\", container_name=\"symbology-api\", host=\"symbology-production\"} != \"uvicorn\" != \"log_client_message\"| json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"api {{.level}} {{.caller}}\\t{{.function}}\\t{{.event}}\"",
     "legendFormat": "symbology-api"
    }
   ]
  },
  {
   "title": "Nginx & Uvicorn Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({job=\"container\", container_name=\"symbology-ui\", host=\"symbology-production\"} | json | line_format \"{{.log}}\" | json log | line_format \"{{.timestamp}}\\t{{.level}}\\t{{.log}}\"[$__auto]))",
     "legendFormat": "{{detected_level}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"symbology-api\", host=\"symbology-production\"} |= \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))"
    }
   ]
  },
  {
   "title": "Nginx & Uvicorn Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"container\", container_name=\"symbology-ui\", host=\"symbology-production\"} | json | line_format \"{{.log}}\" | json log | line_format \"ui nginx\\t{{.detected_level}}\\t{{.log}}\"",
     "legendFormat": "symbology-api"
    },
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"symbology-api\", host=\"symbology-production\"} |= \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))"
    }
   ]
  }
 ]
}