#!/usr/bin/env zsh
export ZPLUG_HOME=${ZPLUG_HOME:=$HOME/.zplug}

# echo "zplug home is $ZPLUG_HOME"

source $ZPLUG_HOME/init.zsh

zplug "jeffreytse/zsh-vi-mode"
# Must load fzf.zsh after vimode plugin is initialized
zvm_after_init_commands+=('source <(fzf --zsh)')

zplug load

#  if $ZPLUG_HOME/repos is empty, run zplug install
if [ -d "$ZPLUG_HOME/repos" ] && [ -z "$(ls -A "$ZPLUG_HOME/repos")" ]; then
    echo "Installing zsh plugins"
    zplug install
fi

# echo "zplug loaded"
