- name: Open passwords file
  include_vars:
    file: "{{ vm_passwords_file }}"
    name: vault
  no_log: true

- name: Get encrypted password
  set_fact:
    cyphertext: "{{ vault.vms[item.hostname].user_password }}"
  no_log: true

- name: Decrypt password
  set_fact:
    decrypted: "{{ cyphertext | unvault(vault_password) }}"
  no_log: true

- name: Render cloud-init templates
  template:
    src: "templates/{{ template_name }}.j2"
    dest: "{{ cloudinit_tmp.path }}/{{ item.hostname }}-{{ template_name }}"
  loop:
    - "metadata.yaml"
    - "network-config.yaml"
    - "userdata.yaml"
  loop_control:
    loop_var: template_name
    label: "Writing {{ cloudinit_tmp.path }}/{{ item.hostname }}-{{ template_name }}"
  vars:
    user_password: "{{ decrypted }}"
