- name: Check if passwords file exists"
  stat:
    path: "{{ vm_passwords_file }}"
  register: vault_file
  when: not ansible_check_mode

- name: Initialize passwords file with empty structure
  copy:
    content: "vms: {}\n"
    dest: "{{ vm_passwords_file }}"
    mode: "0600"
    force: false # Don't overwrite if exists
  when: not vault_file.stat.exists

- name: Check for existing user password
  shell: |
    yq -e '.vms.{{ item.hostname }}.user_password' {{ vm_passwords_file }}
  register: password_check
  failed_when: false
  changed_when: false

- set_fact:
    password_not_set: "{{ password_check.rc != 0 }}"

- name: Generate password
  command: openssl rand -base64 24
  register: plaintext
  when: password_not_set

- name: Encrypt password
  set_fact:
    cyphertext: "{{ plaintext.stdout | vault(vault_password) }}"
  when: password_not_set

- name: Write encrypted password to passwords file
  shell: |
    yq -i '.vms.{{ item.hostname }}.user_password = "{{ cyphertext }}"' {{ vm_passwords_file }}
  when: password_not_set
