# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$directory\
$fill\
$python\
$git_branch\
$git_state\
$git_status\
$time\
$line_break $character"""

[username]
show_always = true
style_user = "bright-blue"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bright-black"
format = "[ 🌀 $hostname]($style) "

[directory]
style = "blue"
truncation_length = 5
truncate_to_repo = false
format = "$path(bright-white)"

[character]
success_symbol = "[>](bold bright-black) "
error_symbol = "[>](bold bright-black) "
vimcmd_symbol = "[:](bold bright-red) "

[fill]
symbol = " "

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "bright-blue"

[git_state]
format = '[$state \($progress_current/$progress_total\)]($style) '

[git_status]
style = "green"
untracked = "[$count U](red)[ / ](white)"
modified = "[$count M](yellow)"
staged = "[ / ](white)[$count S](green)"
diverged = '\[!!!\] '
ahead = '\[$count ahead\] '
behind = '\[$count behind\] '
format = '[$ahead_behind](purple)$untracked$modified$staged --(bright-black) '

[cmd_duration]
format = '[\($duration\)]($style)'
style = "bright-yellow"

[time]
disabled = false
style = "bright-black"
utc_time_offset = "0"
format = '[$time UTC]($style)'

[shell]
disabled = false
format = ' [$indicator]($style)'

[python]
disabled = false
