apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the upstream operator kustomize base
resources:
  - ../../../../../oss/databasus/operator/config/default

namespace: databasus

images:
  - name: controller
    newName: databasus-operator
    newTag: latest

patches:
  - path: manager-patch.yaml
    target:
      kind: Deployment
