_rebuild:
    nerdctl compose -f traggo-compose.yaml build

up: _rebuild
    nerdctl compose -f traggo-compose.yaml up -d

down:
    nerdctl compose -f traggo-compose.yaml down

logs *ARGS:
    nerdctl compose -f traggo-compose.yaml logs {{ARGS}}

