# shellcheck shell=bash
# shellcheck disable=SC2148,SC2035,SC1083
# set dot-env load

up: _ensure-data-dir 
    nerdctl compose -f timescaledb-compose.yaml up --env-file ~/.files/homelab/services/timescaledb/.env --detach

down:
    nerdctl compose -f timescaledb-compose.yaml down

logs *ARGS: # just logs-db -f
    nerdctl compose -f timescaledb-compose.yaml logs {{ARGS}}

# Configure the data dir owner
# upstream timescaledb image uses a nonstandard user
_ensure-data-dir:
    mkdir -p timescaledb-data
    sudo chown -R 100999:100999 timescaledb-data


