services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescaledb-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-6432}:5432
    volumes:
      - ./timescaledb-data:/var/lib/postgresql/data
    networks:
      - lofi-lab-network

networks:
  lofi-lab-network:
    driver: bridge
