apiVersion: databasus.databasus.io/v1alpha1
kind: Storage
metadata:
  name: rustfs
  namespace: databasus
spec:
  name: linode
  type: S3
  s3:
    bucket: zen-cluster-backups
    prefix: databasus
    region: us-east-1
    endpoint: http://us-sea-1.linodeobjects.com
    accessKeySecretRef:
      name: rustfs-credentials
      key: access-key
    secretKeySecretRef:
      name: rustfs-credentials
      key: secret-key
