apiVersion: databasus.databasus.io/v1alpha1
kind: Notifier
metadata:
  name: operator-discord
  namespace: databasus
spec:
  name: Operator Discord
  type: DISCORD
  discord:
    webhookURLSecretRef:
      name: discord-webhook
      key: url
