services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.listen-address=0.0.0.0:9090"
      - "--web.external-url=http://0.0.0.0:9090"


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_PORT:-3100}:3100"
    environment:
      - LISTEN_ADDR=0.0.0.0
    restart: unless-stopped
    volumes:
      - loki_data:/loki
      - ./config:/etc/loki
    command:
      - "--config.file=/etc/loki/loki-config.yaml"

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "${BLACKBOX_EXPORTER_PORT:-9115}:9115"
    restart: unless-stopped
    volumes:
      - ./config:/etc/blackbox-exporter
    command:
      - "--config.file=/etc/blackbox-exporter/blackbox-config.yaml"
      - "--web.listen-address=0.0.0.0:9115"
      - "--web.external-url=http://0.0.0.0:9115"

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
